---

- name: create database
  mysql_db: name={{ item }} state=present login_user=root login_password={{ MYSQL_ROOT }}
  with_items:
    - mailserver

- name: create user mail mysql
  mysql_user: name=mailuser password={{ MYSQL_MAIL }} priv=mailserver.*:ALL host=10.4.2.% state=present login_user=root login_password={{ MYSQL_ROOT }}

- name: copy fille import database mail
  template: src=postfix.j2 dest=/tmp/postfix.sql owner=root group=root mode="u+rw,g+r,o+r"

- name: import database mail
  mysql_db: name=mailserver state=import target=/tmp/postfix.sql name=mailserver login_user=root login_password={{ MYSQL_ROOT }}

