---
# confgig php

- name: Copie des fichier de php
  template: src=php.j2 dest=/etc/php/7.0/fpm/pool.d/{{ DOMAIN | replace(".", "-") }}.conf owner=root group=root mode="u+rw,g+r,o+r"
  notify:
    - restart php-fpm

